mongodb_atlas_public_key  = "your-mongodb-atlas-public-key"
mongodb_atlas_private_key = "your-mongodb-atlas-private-key"
mongodb_atlas_org_id      = "your-mongodb-atlas-org-id"
mongodb_connection_string = "your-mongodb-connection-string"
mongodb_database          = "your-mongodb-database"
